export const industries = {
  construction: {
    slug:       "construction",
    name:       "Construction",
    regulation: "EN 15804 / ESPR 2024",
    deadline:   "2027",
    color:      "bg-amber-50 text-amber-700 border-amber-200",
    heroText:   "Meet EPD and ESPR requirements for every structural product — steel, concrete, timber, and more.",
    description: "The construction sector faces mandatory Environmental Product Declarations (EPDs) and Digital Product Passports for all structural and building products under ESPR 2024. floilan automates embodied carbon calculation, material declarations, and end-of-life data collection across your entire product catalogue.",
    challenges: [
      "Manual EN 15804 carbon calculations taking 3+ days per product",
      "No single system to store and share EPD data with specifiers",
      "Multiple regulatory standards (ESPR, REACH, RoHS) with conflicting data requirements",
      "Supply chain data gaps making lifecycle assessment impossible",
    ],
    outcomes: [
      { metric: "68%", label: "reduction in EPD preparation time" },
      { metric: "100%", label: "of structural products DPP-ready" },
      { metric: "3x",  label: "faster planning submission approval" },
    ],
    features: [
      "EN 15804 lifecycle assessment automation",
      "BIM data integration (Autodesk Revit connector)",
      "REACH & RoHS compliance checks",
      "Supplier data collection portal",
      "One-click EPD PDF generation",
      "QR code for on-site product scanning",
    ],
  },
  batteries: {
    slug:       "batteries",
    name:       "Batteries",
    regulation: "EU Reg 2023/1542",
    deadline:   "Feb 2025 (Phase 1)",
    color:      "bg-blue-50 text-blue-700 border-blue-200",
    heroText:   "Be EU Battery Regulation compliant from day one — for EV, LMT, and industrial batteries.",
    description: "EU Regulation 2023/1542 is the strictest product compliance law ever passed. It requires full Digital Product Passports for all EV, light-means-of-transport, and industrial batteries — including carbon footprint, supply chain due diligence, and state-of-health data. floilan delivers all of it from a single platform.",
    challenges: [
      "Carbon footprint data spanning 40+ supply chain tiers",
      "State of health and remaining useful life tracking at cell level",
      "Cobalt and lithium due diligence documentation",
      "QR-linked DPP mandatory before battery can be sold in EU",
    ],
    outcomes: [
      { metric: "6wks", label: "average time to first compliant DPP" },
      { metric: "40+",  label: "supply chain tiers tracked automatically" },
      { metric: "100%", label: "audit pass rate for floilan battery customers" },
    ],
    features: [
      "EU Reg 2023/1542 full schema implementation",
      "Carbon footprint calculation (cradle to gate)",
      "State of health & remaining capacity tracking",
      "Supply chain due diligence (OECD framework)",
      "QR and NFC tag generation",
      "Battery second-life passport transfer",
    ],
  },
  tyres: {
    slug:       "tyres",
    name:       "Tyres",
    regulation: "EU Tyre Labelling Regulation",
    deadline:   "2026",
    color:      "bg-slate-50 text-slate-700 border-slate-200",
    heroText:   "Automate tyre label compliance and build full lifecycle passports for every SKU.",
    description: "The EU Tyre Labelling Regulation requires standardised fuel efficiency, wet grip, and noise ratings on all tyres — with DPP extensions coming under ESPR. floilan integrates with your testing labs to pull verified data, generate compliant labels, and maintain a full lifecycle record for each tyre model.",
    challenges: [
      "Manual label data entry across hundreds of seasonal SKUs",
      "Testing lab data in inconsistent formats",
      "End-of-life and retreading data not captured",
      "Multi-market labelling requirements (EU vs UK)",
    ],
    outcomes: [
      { metric: "90%", label: "faster label data preparation" },
      { metric: "Zero", label: "manual data entry for lab-verified values" },
      { metric: "EU+UK", label: "dual-market label compliance" },
    ],
    features: [
      "EU Tyre Label Regulation automated data mapping",
      "Lab data API integration",
      "Fuel efficiency, wet grip, noise classification",
      "End-of-life and retreading record",
      "UK vs EU label variant management",
      "QR-linked DPP for trade customers",
    ],
  },
  furniture: {
    slug:       "furniture",
    name:       "Furniture",
    regulation: "ESPR 2024",
    deadline:   "Jan 2026",
    color:      "bg-orange-50 text-orange-700 border-orange-200",
    heroText:   "Meet ESPR furniture requirements with repairability scores, material declarations, and DPPs.",
    description: "ESPR 2024 will require furniture manufacturers to publish Digital Product Passports covering durability, repairability, material composition, and end-of-life instructions. floilan provides a furniture-specific DPP builder pre-mapped to ESPR requirements — with a repairability score calculator included.",
    challenges: [
      "No standardised way to communicate repairability and spare part availability",
      "Material composition data scattered across supplier databases",
      "REACH compliance for surface treatments and finishes",
      "Disassembly instructions not digitised or linked to product",
    ],
    outcomes: [
      { metric: "100%", label: "ESPR furniture schema coverage" },
      { metric: "4hrs", label: "average time to create first DPP" },
      { metric: "Auto", label: "repairability score calculation" },
    ],
    features: [
      "ESPR furniture DPP template",
      "Repairability score calculator (10-point scale)",
      "Material composition declaration",
      "REACH restricted substances check",
      "Disassembly instruction upload & linking",
      "Spare parts availability registry",
    ],
  },
  fashion: {
    slug:       "fashion",
    name:       "Fashion & Textiles",
    regulation: "ESPR / Ecodesign",
    deadline:   "Jul 2026",
    color:      "bg-rose-50 text-rose-700 border-rose-200",
    heroText:   "Full fibre-to-store transparency for every SKU — ESPR compliant, consumer-ready.",
    description: "ESPR Ecodesign requirements for textiles will mandate Digital Product Passports covering fibre composition, country of origin, care instructions, microplastic shedding, and circularity information. floilan handles the full pipeline — from supplier fibre data collection to consumer-facing scannable garment labels.",
    challenges: [
      "Fibre data spanning 14+ supplier countries in inconsistent formats",
      "Microplastic shedding data not collected at garment level",
      "Per-SKU care labelling compliance across markets",
      "No scalable way to manage DPPs for 2,000+ seasonal SKUs",
    ],
    outcomes: [
      { metric: "2,400+", label: "SKUs passported per season" },
      { metric: "14",    label: "supplier countries connected via portal" },
      { metric: "1wk",   label: "to DPP-ready full collection" },
    ],
    features: [
      "ESPR textiles DPP template",
      "Supplier fibre data collection portal",
      "Microplastic shedding data capture",
      "Multi-language care label generation",
      "Circularity & take-back programme linking",
      "Consumer-facing QR garment passport",
    ],
  },
};

export type IndustrySlug = keyof typeof industries;
export type IndustryData = (typeof industries)[IndustrySlug];
